#!/usr/bin/env node
/**
 * Bootstrap .env.local from the logged-in Stripe CLI sandbox.
 * Does not print secret values. Does not overwrite keys that are already set.
 */
import { randomBytes, randomUUID } from 'node:crypto';
import { execSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

const envPath = join(process.cwd(), '.env.local');

function parseEnv(text) {
  const out = {};
  for (const line of text.split('\n')) {
    if (!line || line.trim().startsWith('#') || !line.includes('=')) continue;
    const idx = line.indexOf('=');
    out[line.slice(0, idx).trim()] = line.slice(idx + 1);
  }
  return out;
}

function parseTomlKey(text, key) {
  const match = text.match(new RegExp(`^${key}\\s*=\\s*(.+)`, 'm'));
  return (match?.[1] ?? '').trim().replace(/^['"]|['"]$/g, '');
}

function git(value) {
  try {
    return execSync(`git config --get ${value}`, { encoding: 'utf8' }).trim();
  } catch {
    return '';
  }
}

function usableSecret(value) {
  return /^(sk|rk)_(test|live)_/.test(value || '');
}

const existing = existsSync(envPath) ? parseEnv(readFileSync(envPath, 'utf8')) : {};
const stripeToml = readFileSync(join(homedir(), '.config/stripe/config.toml'), 'utf8');
const stripeSecret = parseTomlKey(stripeToml, 'test_mode_api_key');

const next = {
  NEXT_PUBLIC_SITE_URL: existing.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000',
  STRIPE_SECRET_KEY: usableSecret(existing.STRIPE_SECRET_KEY) ? existing.STRIPE_SECRET_KEY : stripeSecret,
  ADMIN_EMAILS: existing.ADMIN_EMAILS || git('user.email'),
  CRON_SECRET: existing.CRON_SECRET || randomBytes(24).toString('hex'),
  FRAUD_SALT: existing.FRAUD_SALT || randomUUID(),
  EMAIL_FROM: existing.EMAIL_FROM || 'Project Arena <arena@localhost>',
  NEXT_PUBLIC_SUPABASE_URL: existing.NEXT_PUBLIC_SUPABASE_URL || '',
  NEXT_PUBLIC_SUPABASE_ANON_KEY: existing.NEXT_PUBLIC_SUPABASE_ANON_KEY || '',
  SUPABASE_SECRET_KEY: existing.SUPABASE_SECRET_KEY || existing.SUPABASE_SERVICE_ROLE_KEY || '',
  STRIPE_WEBHOOK_SECRET: existing.STRIPE_WEBHOOK_SECRET || '',
};

const lines = [
  '# Generated by scripts/setup-env.mjs. Secrets are gitignored.',
  `NEXT_PUBLIC_SITE_URL=${next.NEXT_PUBLIC_SITE_URL}`,
  `STRIPE_SECRET_KEY=${next.STRIPE_SECRET_KEY}`,
  `STRIPE_WEBHOOK_SECRET=${next.STRIPE_WEBHOOK_SECRET}`,
  `ADMIN_EMAILS=${next.ADMIN_EMAILS}`,
  `CRON_SECRET=${next.CRON_SECRET}`,
  `FRAUD_SALT=${next.FRAUD_SALT}`,
  `EMAIL_FROM=${next.EMAIL_FROM}`,
  `NEXT_PUBLIC_SUPABASE_URL=${next.NEXT_PUBLIC_SUPABASE_URL}`,
  `NEXT_PUBLIC_SUPABASE_ANON_KEY=${next.NEXT_PUBLIC_SUPABASE_ANON_KEY}`,
  `SUPABASE_SECRET_KEY=${next.SUPABASE_SECRET_KEY}`,
];

writeFileSync(envPath, `${lines.join('\n')}\n`);

const set = Object.entries(next)
  .filter(([, value]) => Boolean(value))
  .map(([key]) => key);
const missing = Object.entries(next)
  .filter(([, value]) => !value)
  .map(([key]) => key);

console.log('Wrote .env.local');
console.log('Set:', set.join(', ') || '(none)');
console.log('Still empty:', missing.join(', ') || '(none)');
if (!next.STRIPE_SECRET_KEY) {
  console.log('Stripe: run `stripe sandbox create --from-git --non-interactive` then re-run this script.');
}
if (!next.NEXT_PUBLIC_SUPABASE_URL) {
  console.log('Supabase: paste NEXT_PUBLIC_SUPABASE_URL, NEXT_PUBLIC_SUPABASE_ANON_KEY, SUPABASE_SECRET_KEY, then run schema.sql.');
}
if (!next.STRIPE_WEBHOOK_SECRET) {
  console.log('Webhook: `stripe listen --forward-to localhost:3000/api/stripe/webhook` and copy the whsec_ value.');
}
if (!next.ADMIN_EMAILS) {
  console.log('Admin: set ADMIN_EMAILS to your Builder login email.');
}
